"""unique_document_chunk_index

Revision ID: 2e1482525d09
Revises: 744b28978125
Create Date: 2026-10-10 20:56:05.196797

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e1482525d09"
down_revision: str | Sequence[str] | None = "744b28978125"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_chunk_index', 'document_chunks', ['document_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_chunk_index', 'document_chunks', type_='unique')
    # ### end Alembic commands ###
