"""add_updated_at_timestamps

Revision ID: 744b28978125
Revises: 791aa19f3d22
Create Date: 2026-10-09 19:28:09.069690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.database_models
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '744b28978125'
down_revision: Union[str, Sequence[str], None] = '791aa19f3d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clause_reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clauses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('clauses', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=app.models.database_models.VectorType(dim=768),
               existing_nullable=True)
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.alter_column('clauses', 'embedding',
               existing_type=app.models.database_models.VectorType(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    op.drop_column('clauses', 'updated_at')
    op.drop_column('clause_reviews', 'updated_at')
    # ### end Alembic commands ###
