"""add_foreign_key_indexes

Revision ID: 791aa19f3d22
Revises: 8d25bf777106
Create Date: 2026-10-04 21:31:04.163572

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '791aa19f3d22'
down_revision: str | Sequence[str] | None = '8d25bf777106'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_document_id'), 'automation_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_document_id'), 'chat_messages', ['document_id'], unique=False)
    op.create_index(op.f('ix_clause_reviews_clause_id'), 'clause_reviews', ['clause_id'], unique=False)
    op.create_index(op.f('ix_clause_reviews_document_id'), 'clause_reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_clauses_document_id'), 'clauses', ['document_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_document_id'), 'compliance_checks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_extracted_text_document_id'), 'extracted_text', ['document_id'], unique=False)
    op.create_index(op.f('ix_legal_references_document_id'), 'legal_references', ['document_id'], unique=False)
    op.create_index(op.f('ix_reports_document_id'), 'reports', ['document_id'], unique=False)
    op.create_index(op.f('ix_risk_flags_clause_id'), 'risk_flags', ['clause_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_flags_clause_id'), table_name='risk_flags')
    op.drop_index(op.f('ix_reports_document_id'), table_name='reports')
    op.drop_index(op.f('ix_legal_references_document_id'), table_name='legal_references')
    op.drop_index(op.f('ix_extracted_text_document_id'), table_name='extracted_text')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_compliance_checks_document_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_clauses_document_id'), table_name='clauses')
    op.drop_index(op.f('ix_clause_reviews_document_id'), table_name='clause_reviews')
    op.drop_index(op.f('ix_clause_reviews_clause_id'), table_name='clause_reviews')
    op.drop_index(op.f('ix_chat_messages_document_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_automation_runs_document_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    # ### end Alembic commands ###
