"""initial_schema_baseline

Revision ID: 8d25bf777106
Revises:
Create Date: 2026-10-03 19:49:50.006423

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.database_models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d25bf777106'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clause_reviews',
    sa.Column('id', app.models.database_models.GUID(), nullable=False),
    sa.Column('clause_id', app.models.database_models.GUID(), nullable=False),
    sa.Column('document_id', app.models.database_models.GUID(), nullable=False),
    sa.Column('user_id', app.models.database_models.GUID(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_audit_logs_document_id_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_automation_runs_doc_workflow'), table_name='automation_runs')
    op.alter_column('chat_messages', 'citations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_chat_messages_conversation'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_document'), table_name='chat_messages')
    op.drop_index(op.f('idx_clauses_document_id'), table_name='clauses')
    op.drop_index(op.f('idx_clauses_embedding'), table_name='clauses', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('deep_extractions', 'deal_terms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('deep_extractions', 'obligations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('deep_extractions', 'risk_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('deep_extractions', 'missing_protections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('deep_extractions', 'redline_suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_deep_extractions_document'), table_name='deep_extractions')
    op.drop_index(op.f('idx_document_chunks_chunk_index'), table_name='document_chunks')
    op.drop_index(op.f('idx_document_chunks_document_id'), table_name='document_chunks')
    op.alter_column('documents', 'parties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('documents', 'key_dates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('documents', 'missing_sections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_documents_status'), table_name='documents')
    op.drop_index(op.f('idx_documents_user_id'), table_name='documents')
    op.alter_column('extracted_text', 'parsing_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.drop_index(op.f('idx_risk_flags_clause_id'), table_name='risk_flags')
    op.drop_constraint(op.f('fk_users_auth'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_users_auth'), 'users', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_index(op.f('idx_risk_flags_clause_id'), 'risk_flags', ['clause_id'], unique=False)
    op.alter_column('extracted_text', 'parsing_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.create_index(op.f('idx_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('idx_documents_status'), 'documents', ['status'], unique=False)
    op.alter_column('documents', 'missing_sections',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'key_dates',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'parties',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_chunk_index'), 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('idx_deep_extractions_document'), 'deep_extractions', ['document_id'], unique=False)
    op.alter_column('deep_extractions', 'redline_suggestions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('deep_extractions', 'missing_protections',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('deep_extractions', 'risk_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('deep_extractions', 'obligations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('deep_extractions', 'deal_terms',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('idx_clauses_embedding'), 'clauses', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_clauses_document_id'), 'clauses', ['document_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_document'), 'chat_messages', ['document_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_conversation'), 'chat_messages', ['conversation_id'], unique=False)
    op.alter_column('chat_messages', 'citations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_automation_runs_doc_workflow'), 'automation_runs', ['document_id', 'workflow_name'], unique=True)
    op.create_index(op.f('idx_audit_logs_document_id_created_at'), 'audit_logs', ['document_id', 'created_at'], unique=False)
    op.drop_table('clause_reviews')
    # ### end Alembic commands ###
