/**
 * @file page.tsx
 * @description Report page displaying the final legal memo audit summary.
 */

import React from "react";
import Link from "next/link";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function ReportDetailPage({ params }: PageProps) {
  const resolvedParams = await params;
  const docId = resolvedParams.id;

  return (
    <div className="min-h-screen bg-[#faf9f6] text-[#1c1c1c] font-sans p-8">
      {/* Back button and Print options for layout */}
      <div className="max-w-4xl mx-auto mb-6 flex justify-between items-center no-print">
        <Link href={`/documents/${docId}`} className="text-xs text-[#5c5b57] hover:underline uppercase tracking-wider font-semibold">
          &larr; Back to analysis
        </Link>
        <button className="bg-[#0d1b2a] hover:bg-[#1a2f4c] text-[#faf9f6] px-4 py-1.5 text-xs font-semibold uppercase tracking-wider rounded-none transition-colors duration-200">
          Print Memo
        </button>
      </div>

      {/* Main Memo sheet */}
      <div className="max-w-4xl mx-auto bg-white border border-[#e0dfdb] p-12 rounded-none space-y-8 shadow-none">
        {/* Memo Header */}
        <div className="border-b-2 border-[#0d1b2a] pb-6">
          <h1 className="font-serif text-3xl font-normal text-[#0d1b2a] tracking-wide mb-1">
            LEGAL AUDIT MEMORANDUM
          </h1>
          <p className="text-xs text-[#8a8985] uppercase tracking-wider">
            Generated by Legal Analyzer automated triage platform
          </p>
        </div>

        {/* Memo Fields */}
        <div className="grid grid-cols-2 gap-4 text-xs">
          <div>
            <span className="block text-[#8a8985] uppercase font-semibold">To:</span>
            <span className="text-sm font-semibold">Internal Operations Team</span>
          </div>
          <div>
            <span className="block text-[#8a8985] uppercase font-semibold">Date:</span>
            <span className="text-sm font-semibold">July 8, 2026</span>
          </div>
          <div>
            <span className="block text-[#8a8985] uppercase font-semibold">Document Ref:</span>
            <span className="text-sm font-mono font-semibold">{docId}</span>
          </div>
          <div>
            <span className="block text-[#8a8985] uppercase font-semibold">Safety Score:</span>
            <span className="text-sm font-mono font-bold text-green-700">92 / 100</span>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="space-y-3">
          <h2 className="font-serif text-xl text-[#0d1b2a] border-b border-[#e0dfdb] pb-2">Executive Summary</h2>
          <p className="text-xs text-[#5c5b57] leading-relaxed">
            The document under review is a standard Mutual Non-Disclosure Agreement. Based on our analysis, the document represents low exposure and is safe to execute. Reciprocal provisions for confidentiality, duration, governing law, and limitations of liability are fully present.
          </p>
        </div>

        {/* Critical Recommendations */}
        <div className="space-y-3">
          <h2 className="font-serif text-xl text-[#0d1b2a] border-b border-[#e0dfdb] pb-2">Key Recommendations</h2>
          <ol className="list-decimal pl-5 text-xs text-[#5c5b57] space-y-2">
            <li>Ensure Wilmington, Delaware is an acceptable jurisdiction for your operations before formal execution.</li>
            <li>No amendments are strictly necessary, as standard mutual clauses protect both parties adequately.</li>
          </ol>
        </div>

        {/* Sign-off footer */}
        <div className="border-t border-[#e0dfdb] pt-6 text-[10px] text-[#8a8985] leading-relaxed">
          <p>
            <strong>Disclaimer:</strong> This automated memo assists internal review by highlighting common legal patterns and risk metrics. It does not replace independent legal advice. The user accepts full responsibility for decisions made based on this output.
          </p>
        </div>
      </div>
    </div>
  );
}

